fix(system): ensure robot button light on after setup
Opentrons/buildroot pull request #39
Opened 2019-09-12 18:33 UTC by b-cooper

Ensure that button light is set to blue when gpio setup is stopped via system control.

2019-09-12 19:20 UTC, sfoster1 approved these changes
This code looks fine as long as it works - I'm just slightly concerned about how [the docs](https://docs.python.org/3/library/atexit.html) say these functions happen when the program terminates normally, but systemd will stop this using sigterm. Might have to use a signal handler.

2019-09-13 00:22 UTC, sfoster1 requested changes
I think you have git stuff in the content?

2019-09-13 00:22 UTC, sfoster1 commented on board/opentrons/ot2/rootfs-overlay/usr/bin/ot-blinkenlights
> +>>>>>>> afbcae193e3824c08cc8c5d5fc631e2424e5da27
Is this intended?

2019-09-13 16:24 UTC, sfoster1 requested changes

2019-09-13 16:24 UTC, sfoster1 commented on board/opentrons/ot2/rootfs-overlay/usr/bin/ot-blinkenlights
> +    gpio.set_button_light(blue=True)
Also need to exit the program here, probably using `os._exit` since sighandlers in python (well, and everywhere else) can happen anywhere in the guts of any call

2019-09-16 18:47 UTC, sfoster1 requested changes

2019-09-16 18:47 UTC, sfoster1 commented on board/opentrons/ot2/rootfs-overlay/usr/bin/ot-blinkenlights
> +    os._exit()
Per [the docs](https://docs.python.org/2/library/os.html#os._exit) this requires an exit status argument and indeed systemd shows the service stop having a big traceback.

2019-09-16 18:52 UTC, b-cooper commented on board/opentrons/ot2/rootfs-overlay/usr/bin/ot-blinkenlights
> +    os._exit()
```suggestion
    os._exit(0)
```

2019-09-16 18:52 UTC, sfoster1 commented on board/opentrons/ot2/rootfs-overlay/usr/bin/ot-blinkenlights
> +    os._exit()
👍

2019-09-16 18:56 UTC, sfoster1 approved these changes
Tested, LGTM

2019-09-16 20:54 UTC, merged