Add python-dotenv package
Opentrons/buildroot pull request #82
Opened 2020-04-09 15:36 UTC by amitlissack

Load environment variables from a file. Used by robot-server.

2020-04-09 17:45 UTC, sfoster1 commented on package/python-typing/python-typing.mk
> +PYTHON_TYPING_VERSION = 3.7.4.1
doesn't the pypi typing module not do anything on python >3.5? Per its readme page [on pypi](https://pypi.org/project/typing/)

2020-04-09 17:45 UTC, sfoster1 approved these changes
looks good other than the typing thing

2020-04-09 18:09 UTC, sfoster1 requested changes
Oh actually looks like `python-dotenv` isn't selected in the ot2 defconfig so it's not actually included in the build

2020-04-09 18:43 UTC, amitlissack commented
> Oh actually looks like `python-dotenv` isn't selected in the ot2 defconfig so it's not actually included in the build

Gosh sarnit!

2020-04-09 20:35 UTC, amitlissack commented
> looks good other than the typing thing

I've removed the typing commit and added the package for realsies.

2020-04-10 16:27 UTC, mcous approved these changes
LGTM

2020-04-13 19:31 UTC, sfoster1 approved these changes
LGTM, build looks ok tested on my robot

2020-04-13 19:56 UTC, merged